package db;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;

public class CreateDB {
	Connection conn = null;
	private Statement st = null;
	
	String JDBC_DRIVER =  "org.h2.Driver";
	String DB_URL = "jdbc:h2:~/ShowCaseDB";
	//DB credentials
	 final String USER = "sa";
	 final String PASS = "";
	 
	public void createNewDB(CreateDB newDB) {
		try {
			Class.forName(JDBC_DRIVER);
			conn = DriverManager.getConnection(DB_URL, USER, PASS);
			System.out.println("Connection succesful!");
			st = conn.createStatement();
			
			//drop table if it exists
			final String sqlDeleteDB = "DROP TABLE IF EXISTS OrderTable;\n"+"DROP TABLE IF EXISTS Gebruiker;\n";
			final String sqlCreateDB = "CREATE TABLE OrderTable(ordernummer int GENERATED BY DEFAULT AS IDENTITY, artikel varchar(255) NOT NULL, omschrijving varchar(255), datum date NOT NULL, prijs numeric(10, 2) NOT NULL, typeBetaling varchar(255) NOT NULL, orderStatus varchar(255) NOT NULL, gebGebruikerNummer int NOT NULL, PRIMARY KEY (ordernummer));"+
					"CREATE TABLE Gebruiker (gebruikerNummer int GENERATED BY DEFAULT AS IDENTITY, naam varchar(100) NOT NULL, adres varchar(255), plaats varchar(255) NOT NULL, emailadres varchar(255) NOT NULL, telefoonnummer varchar(15), contactpersoon varchar(100), website varchar(100), opmerkingen varchar(255), bedrijfsnaam varchar(100), typeGebruiker varchar(255) NOT NULL, PRIMARY KEY (gebruikerNummer));"+
					"ALTER TABLE OrderTable ADD CONSTRAINT FKOrder561404 FOREIGN KEY (gebGebruikerNummer) REFERENCES Gebruiker (gebruikerNummer);";
			st.execute(sqlDeleteDB);
			st.execute(sqlCreateDB);
			
			System.out.println("Database creation successfull!");
			//Clean-up environment
			//st.close();
			//conn.close();
		} catch(SQLException se) {
			//Handle errors for JDBC
			se.printStackTrace();
		} catch(Exception e) {
			//Handle errors for class.forName
			e.printStackTrace();
		} finally {
			//finally block used to close resources
			try {
				if(st!=null) st.close();
			} catch(SQLException se2) {}
			try {
				if(conn!=null) conn.close();
			} catch (SQLException se) {
				se.printStackTrace();
			} 
		}
		System.out.println("Goodbye!");
	}
	public CreateDB() {
		
	}

}
